extends:
  - plugin:@next/next/core-web-vitals
  - xo
  - xo-typescript
  - xo-react
  - plugin:react/jsx-runtime # Prevents "'React' must be in scope when using JSX" errors
  - plugin:tailwindcss/recommended
  - prettier # Must be the last extension

rules:
  tailwindcss/classnames-order: 'off' # Handled by "prettier-plugin-tailwindcss"

overrides:
  # Overrides for R3F components
  - files: './src/components/r3f/**/*.ts?(x)'
    rules:
      react/no-unknown-property: 'off'
