name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    env:
      BUILD_DIRECTORY: out
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
      - name: Bun version
        run: bun --version
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Test (types)
        run: bun run test:types
      - name: Test (lint)
        run: bun run test:lint
      - name: Test (format)
        run: bun run test:format
      - name: Build
        run: bun run build
      - name: Upload static output artifact
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: ./${{env.BUILD_DIRECTORY}}
  glsl:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install ClangFormat
        run: |
          sudo apt update
          sudo apt install -y clang-format
      - name: Test GLSL formatting
        run: ./glsl_format_test.sh
