name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    permissions:
      contents: read
      deployments: write
    env:
      BUILD_DIRECTORY: out
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
      - name: Bun version
        run: bun --version
      - name: Set up ClangFormat
        run: |
          sudo apt update
          sudo apt install -y clang-format
      - name: ClangFormat version
        run: clang-format --version
      - name: Install Bun dependencies
        run: bun install --frozen-lockfile
      - name: Test (types)
        run: bun run test:types
      - name: Test (units)
        run: bun run test:units
      - name: Test (lint)
        run: bun run test:lint
      - name: Test (formatting)
        run: bun run test:format
      - name: Test (GLSL formatting)
        run: ./glsl_format_test.sh
      - name: Build
        run: bun run build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: r3f-satelllte
          directory: ./${{env.BUILD_DIRECTORY}}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload static output artifact
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: ./${{env.BUILD_DIRECTORY}}
